inherits:
  - duplicated

  - utils:base
  - utils:fix
ignore-paths:
  - gunicorn.conf.py

#mypy:
#  run: true

pyorama:
  run: true
mypy:
  options:
    python-version: '3.10'
ruff:
  options:
    target-version: py310
