[tool.black]
line-length = 110
target-version = ["py39"]

[tool.poetry]
name = "redirect"
version = "0.0.0"
description = "Not used"
authors = []

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
gunicorn = "21.2.0"
pyramid = "2.0.2"
c2cwsgiutils = { extras = ["standard", "broadcast", "oauth2"], version = "5.2.3" }
pyramid-mako = "1.1.0"
certifi = "2023.7.22"

[tool.poetry.dev-dependencies]
prospector = { version = "1.10.2", extras = ["with_bandit", "with_mypy"] }
pytest = "7.4.2"

[tool.poetry.plugins."paste.app_factory"]
main = "redirect:main"


[tool.poetry.group.dev.dependencies]
prospector-profile-duplicated = "0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
