[tool.black]
line-length = 110
target-version = ["py38"]

[tool.poetry]
name = "redirect"
version = "0.0.0"
description = "Not used"
authors = []

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
gunicorn = "20.1.0"
pyramid = "2.0"
c2cwsgiutils = {extras = ["standard", "broadcast"], version = "5.0.0"}
pyramid-mako = "1.1.0"

[tool.poetry.dev-dependencies]
prospector = {version = "1.7.7", extras = ["with_bandit", "with_mypy"]}
pylint = "2.14.4"
mypy = "0.961"
flake8 = "4.0.1"
pytest = "7.1.2"

[tool.poetry.plugins."paste.app_factory"]
main = "redirect:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
