[tool.black]
line-length = 110
target-version = ["py38"]

[tool.poetry]
name = "redirect"
version = "0.0.0"
description = "Not used"
authors = []

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
gunicorn = "20.1.0"
pyramid = "2.0.1"
c2cwsgiutils = { extras = ["standard", "broadcast", "oauth2"], version = "5.2.2" }
pyramid-mako = "1.1.0"
certifi = "2023.5.7"

[tool.poetry.dev-dependencies]
prospector = { version = "1.10.2", extras = ["with_bandit", "with_mypy"] }
pytest = "7.3.1"

[tool.poetry.plugins."paste.app_factory"]
main = "redirect:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
