# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.5/c2cciutils/schema.json

checks:
  prettier: false

publish:
  pypi:
    packages: []
  docker:
    dispatch: {}
    images:
      - name: camptocamp/redirect

audit:
  snyk:
    pip_install_arguments:
      - --user
      - --ignore-installed
