name: Rebuild

on:
  schedule:
    - cron: '30 2 * * *'

env:
  DOCKER_BUILDKIT: '1'

jobs:
  rebuild:
    name: Rebuild
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        branch:
          - '1.0'

    env:
      REDIS_URL: redis://localhost:6379

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - name: Build
        run: make build

      - name: Publish
        run: c2cciutils-publish --type=rebuild --branch=${{ matrix.branch }}
